name: Update the server on the VPS
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Only use Node.js v13 since it's on my local machine and VPS machine
        node-version: [13.x]
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install global packages
        run: npm i -g eslint
      - name: Install repository dependencies
        run: npm i
      - name: Lint for any code errors or warnings
        run: eslint src --ext .js --fix
      - name: Test with Jest
        run: npm run test
      - name: Update and hot reload the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: 22
          username: august
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/sharex-server
            git pull
            rm -fr node_modules && rm yarn.lock
            yarn
            pm2 restart sharex-server